services:
  - type: web
    name: myshop-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node index.js
    rootDir: backend
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: ACCESS_TOKEN_EXPIRES_IN
        sync: false
      - key: REFRESH_TOKEN_EXPIRES_IN
        sync: false
      - key: NODE_ENV
        value: production
