services:
  - type: web
    name: myshop-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: MONGO_URI
        value: your_mongo_connection_string
      - key: JWT_SECRET
        value: your_jwt_secret
